version: '3.7'
services:
  auto-m4b:
    hostname: auto-m4b
    container_name: auto-m4b
    volumes:
      - ./config:/config
      - ./temp:/temp
    environment:
      - PUID=1000
      - PGID=1000
      - CPU_CORES=2
      - MAKE_BACKUP=N
      - BOT_TOKEN=
      - CHAT_ID=
    image: johnlucajf/auto-m4b
